src/NerdStore.WebApp.MVC/Controllers/ShoppingCartController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalog.Application.Services;
using NerdStore.Core.Communication.Mediator;
using NerdStore.Core.Messages.CommonMessages.Notifications;
using NerdStore.Sales.Application.Commands;
using NerdStore.Sales.Application.Queries;
using NerdStore.Sales.Application.Queries.ViewModels;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class ShoppingCartController : ControllerBase
    { 
        private readonly IProductAppService _productAppService;
        private readonly IMediatorHandler _mediatorHandler;
        private readonly IOrderQueries _orderQueries;

        public ShoppingCartController(INotificationHandler<DomainNotification> notifications,
                                      IProductAppService productAppService, 
                                      IMediatorHandler mediatorHandler, IOrderQueries orderQueries) : base(notifications, mediatorHandler)
        {
            _productAppService = productAppService;
            _mediatorHandler = mediatorHandler;
            _orderQueries = orderQueries;
        }

        [Route("my-cart")]
        public async Task<IActionResult> Index()
        {
            return View(await _orderQueries.GetShoppingCartByCustomerId(CustomerId));
        }

        [HttpPost]
        [Route("my-cart")]
        public async Task<IActionResult> AddItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetProductById(id);
            if (product == null) return BadRequest();

            if (product.StockQuantity < quantity)
            {
                TempData["Error"] = "Stock not available";
                return RedirectToAction("ProductDetail", "Shop", routeValues: new { id }); 
            }

            var command = new AddOrderItemCommand(CustomerId, product.Id, product.Name, quantity, product.Price);

            await _mediatorHandler.SendCommand(command);

            if (ValidOperation()) return RedirectToAction("Index", "Shop");
            
            TempData["Error"] =  GetErrorMessage();
            return RedirectToAction("ProductDetail", "Shop", routeValues: new { id });

        }


        [HttpPost]
        [Route("remove-item")]
        public async Task<IActionResult> RemoveItem(Guid id)
        {
            var product = await _productAppService.GetProductById(id);
            if (product == null) return BadRequest();

            var command = new RemoveItemOrderCommand(CustomerId,product.Id);
            await _mediatorHandler.SendCommand(command);

            if (ValidOperation()) return RedirectToAction("Index");

            return View("Index", await _orderQueries.GetShoppingCartByCustomerId(CustomerId));

        }

        [HttpPost]
        [Route("update-item")]
        public async Task<IActionResult> UpdateItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetProductById(id);
            if (product == null) return BadRequest();

            var command = new UpdateItemOrderCommand(CustomerId, id, product.Id, quantity);
            await _mediatorHandler.SendCommand(command);

            if (ValidOperation()) return RedirectToAction("Index");

            return View("Index", await _orderQueries.GetShoppingCartByCustomerId(CustomerId));

        }

        [HttpPost]
        [Route("apply-coupon")]
        public async Task<IActionResult> ApplyCoupon(string coupon,Guid id)
        {
            var command = new ApplyCouponOrderCommand(CustomerId, id, coupon);
            await _mediatorHandler.SendCommand(command);

            if (ValidOperation()) return RedirectToAction("Index");

            return View("Index", await _orderQueries.GetShoppingCartByCustomerId(CustomerId));


        }

        [Route("PurchaseSummary")]
        public async Task<IActionResult> PurchaseSummary()
        {
            return View(await _orderQueries.GetShoppingCartByCustomerId(CustomerId));
        }

        [HttpPost]
        [Route("")]
        public async Task<IActionResult> StartOrder(ShoppingCartViewModel cartViewModel)
        {

            var cart = await _orderQueries.GetShoppingCartByCustomerId(CustomerId);

         
            var command = new StartOrderCommand(cart.OrderId, CustomerId, cart.Total, cart.Payment.CardName,
                                                cart.Payment.CardNumber, cart.Payment.CardName, cart.Payment.ExpirationDate, cart.Payment.CvvCode);


            await _mediatorHandler.SendCommand(command);

            if (ValidOperation()) return RedirectToAction("Index", "Order");
         
            return View("PurchaseSummary", await _orderQueries.GetShoppingCartByCustomerId(CustomerId));
        
        }
    }
}

src/NerdStore.WebApp.MVC/Extensions/SummaryViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Messages.CommonMessages.Notifications;

namespace NerdStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifications = await Task.FromResult(_notifications.GetNotifications());
            notifications.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

src/NerdStore.WebApp.MVC/Views/ShoppingCart/Index.cshtml
@model NerdStore.Sales.Application.Queries.ViewModels.ShoppingCartViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">

            <vc:summary />

            @{
                if (Model?.Items != null)
                {
                    <h3>OrderId= @Model.OrderId</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Total</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            @{
                                foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td class="col-sm-5 col-md-5">
                                            <div class="media">
                                                <div class="media-body">
                                                    <h4 class="media-heading"><a asp-controller="Shop" asp-action="ProductDetail" asp-route-id="@item.ProductId">@item.ProductName</a></h4>
                                                </div>
                                            </div>
                                        </td>

                                        <td class="col-sm-2 col-md-2" style="text-align: center">
                                            <form method="post" asp-controller="ShoppingCart" asp-action="UpdateItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <div class="row" style="float: left">
                                                    <input style="width: 70px" type="text" class="form-control" name="quantity" id="quantity" value="@item.Quantity">
                                                </div>
                                                <div class="row" style="float: right">
                                                    <button type="submit" class="btn btn-success">
                                                        <span class="fas fa-sync"></span>
                                                    </button>
                                                </div>
                                            </form>
                                        </td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.UnitPrice.ToString("C")</strong></td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.Total.ToString("C")</strong></td>

                                        <td class="col-sm-1 col-md-1">
                                            <form method="post" asp-controller="ShoppingCart" asp-action="RemoveItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <button type="submit" class="btn btn-danger">
                                                    <span class="fas fa-trash-alt"></span> Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            }

                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td><h5>Sub Total</h5></td>
                                <td class="text-right"><h5><strong>@Model.SubTotal.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td colspan="2">
                                    <form method="post" asp-controller="ShoppingCart" asp-action="ApplyCoupon">
                                        <div class="row" style="float: left">
                                            <input placeholder="Coupon" style="width: 150px" type="text" class="form-control" name="Coupon" id="Coupon" value="@Model.Coupon">
                                            <input type="hidden" id="Id" name="Id" value="@Model.OrderId" />
                                        </div>
                                        <div class="row" style="float: right">
                                            <button type="submit" class="btn btn-success">
                                                <span class="fas fa-sync"></span>
                                            </button>
                                        </div>
                                    </form>
                                </td>
                                <td><h5>Discount</h5></td>
                                <td class="text-right"><h5><strong>@Model.Discount.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <h3>Total</h3>
                                </td>
                                <td class="text-right">
                                    <h3><strong>@Model.Total.ToString("C")</strong></h3>
                                </td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <a asp-controller="Shop" asp-action="Index" class="btn btn-dark">
                                        <span class="fa fa-shopping-cart"></span>Continue Shopping
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="ShoppingCart" asp-action="PurchaseSummary" class="btn btn-success">
                                        <span class="fas fa-play"></span><br /> Check Out Now
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }
                else
                {
                    <div><p>Shopping Cart Empty</p></div>
                }
            }
        </div>
    </div>
</div>

src/NerdStore.WebApp.MVC/Views/ShoppingCart/PurchaseSummary.cshtml
@model NerdStore.Sales.Application.Queries.ViewModels.ShoppingCartViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <vc:summary />

    <div class="row">

        @{
            if (Model.Items.Any())
            {
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Purchase Summary</span>
                        <span class="badge badge-secondary badge-pill" style="background-color: #6c757d; color: white;">@Model.Items.Count</span>
                    </h4>
                    <ul class="list-group mb-3">

                        @{
                            foreach (var item in Model.Items)
                            {
                                <li class="list-group-item d-flex justify-content-between lh-condensed">
                                    <div>
                                        <h6 class="my-0">@item.ProductName</h6>
                                        <small class="text-muted">Quantity: @item.Quantity</small>
                                    </div>
                                    <span class="text-muted">@item.Total.ToString("C")</span>
                                </li>
                            }

                            if (!string.IsNullOrEmpty(Model.Coupon))
                            {
                                <li class="list-group-item d-flex justify-content-between bg-light">
                                    <div class="text-success">
                                        <h6 class="my-0">Coupon Applied</h6>
                                        <small>@Model.Coupon</small>
                                    </div>
                                    <span class="text-success">-@Model.Discount.ToString("C")</span>
                                </li>
                            }

                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total</span>
                                <strong>@Model.Total.ToString("C")</strong>
                            </li>
                        }
                    </ul>

                </div>
                <div class="col-md-8 order-md-1">
                    <form method="post" asp-controller="ShoppingCartController" asp-action="StartOrder">

                        <h4 class="mb-3">Payment</h4>
                        <hr class="mb-4">
                        <div class="row">
                            <img class="img-fluid" src="Images/cards.png">

                        </div>
                        <br /><br />
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label>Card Holder</label>
                                <input asp-for="Payment.CardName" type="text" class="form-control" placeholder="" required="">
                                <small class="text-muted">Complete Name as on Card</small>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label>Card Number</label>
                                <input asp-for="Payment.CardNumber" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label>Expiration Date</label>
                                <input asp-for="Payment.ExpirationDate" type="text" class="form-control" placeholder="" required="">
                            </div>
                            <div class="col-md-3 mb-3">
                                <label>CVV</label>
                                <input asp-for="Payment.CvvCode" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Checkout</button>
                    </form>
                </div>
            }
            else
            {
                <div><p>Shopping Cart Empty</p></div>
            }
        }

    </div>
</div>